// packages/react17/src/pages/page2/page2.tsx
import microAappLogo from '../../assets/micro-app-logo.png'
import './page2.css'

const Page2 = () => {
  return (
    <div>
      <h1>child-react17-page2</h1>
      <div className="child-react17-test-btn">test</div>
      <img src={microAappLogo} alt="micro-app-logo" />
    </div>
  )
}

export default Page2

// packages/angular11/src/app/page2/page2.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-page2',
  templateUrl: './page2.component.html',
  styleUrls: ['./page2.component.sass']
})
export class Page2Component implements OnInit {

  constructor() { }

  btnColor = 'red'

  ngOnInit(): void {
  }

  changeColor () {
    this.btnColor = this.btnColor === 'red' ? 'blue' : 'red'
  }
}

<div>
  <h1>child-angular11-page2</h1>
  <div class="child-angular11-test-btn" (click)="changeColor()" [style.background-color]="btnColor">test</div>
  <img src="/child/angular11/assets/micro-app-logo.png" alt="" />
</div>
