// packages/vue2/src/pages/page2.vue
<template>
  <div>
    <h1>child-vue2-page2</h1>
    <div class="child-vue2-test-btn">test</div>
    <img src="../assets/micro-app-logo.png" alt="micro-app-logo" />
  </div>
</template>

<script>

export default {
  name: 'page2',
  data() {
    return {
    }
  }
}
</script>

<style>
.child-vue2-test-btn {
  height: 40px;
  width: 100px;
  background-color: red;
  border-radius: 10px;
  display: flex;
  justify-content: center;
  align-items: center;
  color: #fff;
  font-size: 20px;
  font-weight: bolder;
  margin: 0 auto;
  user-select: none;
}
</style>

// packages/react17/src/pages/page2/page2.tsx
import microAappLogo from '../../assets/micro-app-logo.png'
import './page2.css'

const Page2 = () => {
  return (
    <div>
      <h1>child-react17-page2</h1>
      <div className="child-react17-test-btn">test</div>
      <img src={microAappLogo} alt="micro-app-logo" />
    </div>
  )
}

export default Page2
